name: MoneyPitPlugin
version: '${project.version}'
main: me.youhavetrouble.moneypit.plugin.MoneyPit
api-version: '1.13'
load: STARTUP
authors: [YouHaveTrouble]
commands:
  moneypit:
    description: MoneyPit command
    usage: /<command>
    permission: moneypit.command
    permission-message: You do not have permission to use this command.
permissions:
  moneypit.command:
    default: op
    description: "Allows access to the /moneypit command."